### ISSUE TITLE
ImportError: No module named 'Generator'

### ISSUE THREAD

**Issue by AmolMavuduru** [vitay/YouTubeFacesDB#1]
After installing the module and running GenerateSubset.py I get the following error, with the stack trace below:

Traceback (most recent call last):
  File "GenerateSubset.py", line 1, in <module>
    from YouTubeFacesDB import generate_ytf_database
  File "/Users/amol/.local/lib/python3.5/site-packages/YouTubeFacesDB-0.0.1-py3.5.egg/YouTubeFacesDB/__init__.py", line 1, in <module>
ImportError: No module named 'Generator'

**Comment by vitay** [comment]
The module was written for Python 2.7. If you want to use it with Python 3, one should modify the imports:

```python
from .Generator import generate_ytf_database
```

If I find some time in the next days, I can do it, it is backwards-compatible.
